name: publish

on:
  push:
    tags:
      - '*'

jobs:
  init:
    strategy:
      matrix:
        # go-version: [1.13.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    outputs:
      tag: ${{ steps.get_tag.outputs.tag }}
    steps:
      # - uses: actions/checkout@master
      #   with:
      #     fetch-depth: 1
      # - name: Install Go
      #   uses: actions/setup-go@v2
      #   with:
      #     go-version: ${{ matrix.go-version }}
      - name: Get TAG
        id: get_tag
        run: echo ::set-output name=TAG::${GITHUB_REF#refs/tags/}
      # - name: Run CI
      #   run: sh ./contrib/ci.sh
      # - name: After Success
      #   run: |
      #     echo "Time to tag images as $TRAVIS_TAG and push remote"

  build-and-push:
    runs-on: ubuntu-latest
    needs: init
    strategy:
      matrix:
        go-version: [1.13.x]
        svc: [
          # edge-auth,
          edge-router,
          of-builder
        ]
    steps:
      - name: Get TAG
        id: get_tag
        run: echo ::set-output name=TAG::${GITHUB_REF#refs/tags/}
      - uses: actions/checkout@v2
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: ghcr.io
      - name: Build and push ${{ matrix.svc }}
        uses: docker/build-push-action@v2
        with:
          context: ./${{ matrix.svc }}
          file: ./${{ matrix.svc }}/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ secrets.DOCKER_USERNAME }}/${{ matrix.svc }}:${{needs.init.outputs.tag}}
            ghcr.io/${{ secrets.DOCKER_USERNAME }}/${{ matrix.svc }}:latest